//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMedico.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Citas
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
        public int Id_paciente { get; set; }
        public int Id_medico { get; set; }
        public int Id_consultorio { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
    
        public virtual Consultorios Consultorios { get; set; }
        public virtual Medicos Medicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
