//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilEmpresa
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string NumeroRegistro { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Moneda { get; set; }
        public string ZonaHoraria { get; set; }
        public byte[] Logo { get; set; }
        public string Calle { get; set; }
        public string Ciudad { get; set; }
        public string CodigoPostal { get; set; }
        public string Pais { get; set; }
    }
}
